addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5

install:
  - export CXX="g++-5" CC="gcc-5"

before_script:
  - mkdir -p build && cd build
  - cmake ..

script:
  - make
